### ISSUE TITLE
galactic coordinates

### ISSUE THREAD

**Issue by rubyvanrooyen** [ska-sa/astrokat#10]
We need to test the implementation of galactic coordinate observations
It is available in katpoint, but remains untested

Information from Sean to do this:
deg:mm:ss.sss  for both b & l 
T11R00C02, gal target ,327:52:35.5556,00:59:15.5556

ephem says that it is radec (15:49:32.32, -53:02:00.4)

**Comment by mserylak** [comment]
Hmm, I do remember seeing targets given in l & b but in decimal degrees, never in HMS DMS...

**Comment by rubyvanrooyen** [comment]
Helper script in astrokat, pull request #90 and #91
