### ISSUE TITLE
no clean exit for start_session

### ISSUE THREAD

**Issue by rubyvanrooyen** [ska-sa/astrokat#12]
The start_session implementation is a function, there is no clean way to create a session object and then exit later

Currently the with statement implementation is the best structure to use, else the SP does not get a capture stop and done and the data stream has to be interrupted explicitly which is undesired

Will it be worth while to implement an end_session option, to allow for easier modular implementations?

**Comment by ajoubertza** [comment]
@rubyvanrooyen As discussed, using a single `with` statement session object will be the safest, so rather go with that option.

**Comment by rubyvanrooyen** [comment]
Implemented in the obs-script-cleanup branch, pull request #13
