### ISSUE TITLE
setup.py missing to pip install astrokat

### ISSUE THREAD

**Issue by wbode-za** [ska-sa/astrokat#14]
A setup.py file is needed to allow CAM to install astrokat as a package.
What are all of the astrokat dependencies?

**Comment by SKAJohanVenter** [comment]
@wbode-za Only saw this issue now. I added a bare bones `setup.py` in PR  https://github.com/ska-sa/astrokat/pull/16 that can be used as is, but should really be expanded.

**Comment by rubyvanrooyen** [comment]
astrokat package now pip installable (karoocamv22 release)
