### ISSUE TITLE
astrokat + python 3

### ISSUE THREAD

**Issue by rubyvanrooyen** [ska-sa/astrokat#25]
Start a parallel develop branch that is python 3.6

**Comment by ajoubertza** [comment]
Good idea to support this.  I suggest we make the code compatible with both Python 2.7 and >= 3.6, rather than trying to maintain two branches.  CAM have plans to migrate, but will still be running 2.7 for while (easily a another year).

**Comment by rubyvanrooyen** [comment]
Seems CAM helped out in the background, running on Py2.7 and Py3
