### ISSUE TITLE
unit and integration tests

### ISSUE THREAD

**Issue by rubyvanrooyen** [ska-sa/astrokat#26]
Implementation of unit nose tests for astrokat through the jenkins interface

**Comment by ajoubertza** [comment]
This is being added in PR #30

**Comment by rubyvanrooyen** [comment]
Now that jenkins is in place and with help from @wbode-za proper nose tests will be implemented with good code coverage

**Comment by rubyvanrooyen** [comment]
Initial implementation done, CAM leading remaining efforts
