### ISSUE TITLE
Changes to input arguments for new observation framework

### ISSUE THREAD

**Issue by rubyvanrooyen** [ska-sa/astrokat#6]
Standard options in sessions that could potentially be removed or updated:

Options to remove since it can is redundant or can cause confusion with SB tags:
* New observation framework will discard all KAT-7 options
```
--mode=MODE           DBE mode to use for experiment, keeps current mode by
                        default [KAT-7 only]
--dbe-centre-freq=DBE_CENTRE_FREQ
                        DBE centre frequency in MHz, used to select coarse
                        band for narrowband modes (unchanged by default)
                        [KAT-7 only]
--no-mask             Keep all correlation products by not applying
                        baseline/antenna mask [KAT-7 only]
```
* Schedule block has a description, do not need an explicit description anymore, the proposal-description should be enough:
```
-d DESCRIPTION, --description=DESCRIPTION
                        Description of observation (default='Imaging run')
```
* Should the user be able to specify the center frequency? Are we able to set the frequency in the correlator?
```
 -f CENTRE_FREQ, --centre-freq=CENTRE_FREQ
                        Delay-tracking centre frequency, in MHz
```

* Noise diode option needs some update, see issue #5 
```
  -n ND_PARAMS, --nd-params=ND_PARAMS
                        Noise diode parameters as
                        '<diode>,<on>,<off>,<period>', in seconds or 'off' for
                        no noise diode firing (default='coupler,10,10,180')
```

**Comment by spassmoor** [comment]
```
-f CENTRE_FREQ, --centre-freq=CENTRE_FREQ
                        Delay-tracking centre frequency, in MHz
```This should be in the observation part of the script (for when we get zoom modes)

```
-d DESCRIPTION, --description=DESCRIPTION
                        Description of observation (default='Imaging run')
``` This should be in the observation part of the script, so that the astronomer can have there own description.

**Comment by rubyvanrooyen** [comment]
The file will now cause an error when an argument is duplicated, no longer silently clobbering each other
We need to discuss duplications such as "operator" and "description"
http://10.97.1.13:8081/tailtask/20181011-0010/progress

Sean suggested that we move some of these items to the YAML file, I like that idea -- similar to what Sharmila does in the catalogue files:
```
# ObserverID: sharmila@ska.ac.za
# csv_description: Science verification - galaxy clusters
# PI_name: Fernando Camilo
# PI_email: fernando@ska.ac.za
# phone:
```

We can add similar structures for user stuff

**Comment by rubyvanrooyen** [comment]
Is there a way to get 'observer' and 'description' from the schedule block information when running on a live system that has CAM?

**Comment by rubyvanrooyen** [comment]
CAM cleaned up inconsistencies between input arguments and schedule block
Astrokat no longer takes additional input parameters, all observational information must be contained in the YAML file
